//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WickhamAthleticsData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int PK_ContentID { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FK_Panel { get; set; }
        public Nullable<int> TextType { get; set; }
    
        public virtual Panel Panel { get; set; }
        public virtual TEXT_TYPE_REF TEXT_TYPE_REF { get; set; }
    }
}
