//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WickhamAthleticsData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int PK_ImageID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FK_Panel { get; set; }
        public string Source { get; set; }
        public Nullable<int> FK_CarouselID { get; set; }
    
        public virtual ImageCarousel ImageCarousel { get; set; }
        public virtual Panel Panel { get; set; }
    }
}
