//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WickhamAthleticsData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel
    {
        public Panel()
        {
            this.Content = new HashSet<Content>();
            this.Image = new HashSet<Image>();
            this.ImageCarousel = new HashSet<ImageCarousel>();
            this.VarSet = new HashSet<VarSet>();
        }
    
        public int PK_PanelID { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<Content> Content { get; set; }
        public virtual ICollection<Image> Image { get; set; }
        public virtual ICollection<ImageCarousel> ImageCarousel { get; set; }
        public virtual ICollection<VarSet> VarSet { get; set; }
    }
}
