//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WickhamAthleticsData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXT_TYPE_REF
    {
        public TEXT_TYPE_REF()
        {
            this.Content = new HashSet<Content>();
            this.VarSet = new HashSet<VarSet>();
        }
    
        public int PK_TextType { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Content> Content { get; set; }
        public virtual ICollection<VarSet> VarSet { get; set; }
    }
}
